import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#bbf",
  },
  subHead: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "center",
    marginBottom: 20,
  },
  settingName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#55f",
  },
  actionButton: {
    borderRadius: 3,
    backgroundColor: "#5555ff",
    padding: 10,
    alignItems: "center",
    minWidth: 100,
    margin: 5,
  },
  cancelButton: {
    borderRadius: 3,
    backgroundColor: "#888",
    padding: 10,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  addNewButton: {
    alignSelf: "flex-end",
    borderRadius: 50,
    backgroundColor: "#5555ff",
    padding: 10,
    alignItems: "center",
    margin: 5,
    aspectRatio: "1/1",
    width: 40,
  },
  flatList: {
    width: "90%",
  },
  timerText: {
    fontSize: 30,
    marginBottom: 20,
  },
  timersContainer: {
    backgroundColor: "#335",
    borderRadius: 30,
    padding: 10,
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#ccf",
    overflow: "auto",
    marginBottom: 20,
    marginTop: 40,
    alignItems: "center",
    flex: 1,
  },
  activeContainer: {
    backgroundColor: "#fff",
    borderRadius: 30,
    padding: 10,
    borderStyle: "solid",
    borderWidth: 3,
    borderColor: "#ccf",
    marginBottom: 20,
    alignItems: "center",
  },
  createTimer: {
    marginBottom: 20,
    width: "100%",
    flex: 1,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#fff",
    padding: 5,
    borderRadius: 5,
  },
  fieldRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    width: "100%",
    justifyContent: "center",
  },
  fieldRowLeft: {
    textAlign: "right",
    alignItems: "flex-end",
    flexGrow: 1,
    maxWidth: "50%",
    minWidth: "50%",
  },
  fieldRowRight: {
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    flexGrow: 1,
  },
  savedTimers: {
    marginBottom: 20,
  },
  activeTimer: {
    justifyContent: "center",
    alignItems: "center",
  },
  textInput: {
    backgroundColor: "#ddf",
    width: 50,
    borderColor: "black",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 10,
    padding: 5,
  },
  listItem: {
    width: "100%",
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#ccc",
    padding: 5,
    borderRadius: 5,
    marginBottom: 5,
  },
  listText: {
    width: "100%",
    flex: 1,
    flexDirection: "column",
    gap: 5,
  },
  progressBar: {
    flexDirection: "column",
    flexWrap: "wrap",
    alignItems: "center",
    borderRadius: 5,
    overflow: "hidden",
    width: 300,
    marginBottom: 20,
    marginTop: 20,
    marginHorizontal: 5,
  },
  intervalScale: {
    height: 8,
    width: 300,
    flexDirection: "row",
    flexWrap: "nowrap",
    justifyContent: "space-between",
  },
  intervalScaleItem: {
    borderRightColor: "#0000FF",
    borderRightWidth: 2,
    flexGrow: 1,
  },
  firstIntervalScaleItem: {
    flexGrow: 1,
    borderRightColor: "#0000FF",
    borderRightWidth: 2,
    borderLeftColor: "#0000FF",
    borderLeftWidth: 2,
  },
  intervalBG: {
    backgroundColor: "#bbbbff",
    padding: 0,
    width: 300,
  },
  interval: {
    height: 20,
    backgroundColor: "#5555ff",
  },
  intervalCompleted: {
    backgroundColor: "#00ff00",
  },
  textIndicator: {
    marginLeft: 10,
  },
  controls: {},
});

export default styles;
