import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#000",
  },
  subHead: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "center",
    marginBottom: 20,
    color: "#aaa",
  },
  settingName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#aaa",
  },
  actionButton: {
    borderRadius: 3,
    backgroundColor: "#353",
    padding: 10,
    alignItems: "center",
    minWidth: 100,
    margin: 5,
  },
  cancelButton: {
    borderRadius: 3,
    backgroundColor: "#222",
    padding: 10,
  },
  buttonText: {
    color: "#aaa",
    fontWeight: "bold",
  },
  addNewButton: {
    alignSelf: "flex-end",
    borderRadius: 50,
    backgroundColor: "#353",
    padding: 10,
    alignItems: "center",
    margin: 5,
    aspectRatio: "1/1",
    width: 40,
  },
  flatList: {
    width: "90%",
  },
  timerText: {
    fontSize: 30,
    marginBottom: 20,
    color: "#aaa",
  },
  timersContainer: {
    backgroundColor: "#000",
    borderRadius: 30,
    padding: 10,
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#555",
    overflow: "auto",
    marginBottom: 20,
    marginTop: 40,
    alignItems: "center",
    flex: 1,
  },
  activeContainer: {
    backgroundColor: "#333",
    borderRadius: 30,
    padding: 10,
    borderStyle: "solid",
    borderWidth: 2,
    borderColor: "#353",
    marginBottom: 20,
    alignItems: "center",
  },
  createTimer: {
    marginBottom: 20,
    width: "100%",
    flex: 1,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#333",
    padding: 5,
    borderRadius: 5,
  },
  fieldRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    width: "100%",
    justifyContent: "center",
  },
  fieldText: {
    color: "#aaa",
  },
  fieldRowLeft: {
    textAlign: "right",
    alignItems: "flex-end",
    flexGrow: 1,
    maxWidth: "50%",
    minWidth: "50%",
  },
  fieldRowRight: {
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    flexGrow: 1,
  },
  savedTimers: {
    marginBottom: 20,
  },
  activeTimer: {
    justifyContent: "center",
    alignItems: "center",
  },
  textInput: {
    backgroundColor: "#777",
    width: 50,
    borderRadius: 10,
    padding: 5,
  },
  listItem: {
    width: "100%",
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#333",
    padding: 5,
    borderRadius: 5,
    marginBottom: 5,
  },
  listText: {
    width: "100%",
    flex: 1,
    flexDirection: "column",
    gap: 5,
    color: "#fff",
  },
  listDescription: {
    color: "#888",
  },
  progressBar: {
    flexDirection: "column",
    flexWrap: "wrap",
    alignItems: "center",
    borderRadius: 5,
    overflow: "hidden",
    width: 300,
    marginBottom: 20,
    marginTop: 20,
    marginHorizontal: 5,
  },
  intervalScale: {
    height: 8,
    width: 300,
    flexDirection: "row",
    flexWrap: "nowrap",
    justifyContent: "space-between",
  },
  intervalScaleItem: {
    borderRightColor: "#888",
    borderRightWidth: 2,
    flexGrow: 1,
  },
  firstIntervalScaleItem: {
    flexGrow: 1,
    borderRightColor: "#888",
    borderRightWidth: 2,
    borderLeftColor: "#888",
    borderLeftWidth: 2,
  },
  intervalBG: {
    backgroundColor: "#111",
    padding: 0,
    width: 300,
  },
  interval: {
    height: 20,
    backgroundColor: "#353",
  },
  intervalCompleted: {
    backgroundColor: "#00ff00",
  },
  textIndicator: {
    marginLeft: 10,
  },
  controls: {},
});

export default styles;
